apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
spec:
  project: default


  source:
    repoURL: https://github.com/poojavkhandare-sudo/argocdapps-project.git
    targetRevision: HEAD
    path: .

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: frontend
